[Chore] Integrate external near-account-id.
near/nearcore pull request #10001
Opened 2023-10-24 19:28 UTC by ruseinov

2023-10-24 20:20 UTC, frol requested changes

2023-10-24 20:20 UTC, frol commented on chain/network/src/store/schema/mod.rs
> +        w.write_all(account_id_ref.as_bytes())
Try this one:

```suggestion
        w.write_all(a.as_bytes())
```

If it works ([it should](https://github.com/near/near-account-id/blob/main/src/account_id_ref.rs#L76)), apply everywhere else

2023-10-24 20:20 UTC, frol commented on runtime/runtime/src/verifier.rs
> -            if transaction.receiver_id.as_ref() != function_call_permission.receiver_id {
You probably don't need `as_ref()` here now at all as there is comparison implementations for AccountIdRef <> str

2023-10-25 10:00 UTC, nagisa commented on Cargo.toml
> +near-account-id = { git = "https://github.com/ruseinov/near-account-id", features = ["internal_unstable", "serde", "borsh"], branch = "ru/chore/len" }
Why not make the relevant change in this PR itself?

2023-10-25 10:03 UTC, nagisa commented
I would like to see the PR description contain the background information on this change – the motivation behind why this change is being made, references to discussion that has taken (if any – so far we've been moving in the direction of making it more monorepo rather than the other way around,) etc.

2023-10-25 13:05 UTC, frol commented
@nagisa near-account-id was created inside nearcore as an attempt to easily reuse this crate in other parts of ecosystem (near-sdk-rs, near-cli-rs, near-jsonrpc-client-rs, …), but with the time passing, I believe that we can release this crate as 1.0 https://github.com/near/near-account-id-rs/issues/5 and extract it from the nearcore 0.x releases.

There are more such 1.0 crates will appear:
* https://github.com/near/near-gas-rs
* https://github.com/near/near-token-rs

This all is part of a bigger initiative to finally make the tooling landscape easy for consumption in on-chain and off-chain apps

2023-10-26 09:25 UTC, frol requested changes

2023-10-26 09:25 UTC, frol commented on chain/network/src/store/schema/mod.rs
> +use near_primitives::account::id::{AccountId, AccountIdRef};
`AccountIdRef` imports are not needed anymore.

2023-10-27 20:19 UTC, ruseinov commented
@frol Some of the workflows need to be approved. The error I'm getting now is kinda strange..

> @nagisa near-account-id was created inside nearcore as an attempt to easily reuse this crate in other parts of ecosystem (near-sdk-rs, near-cli-rs, near-jsonrpc-client-rs, …), but with the time passing, I believe that we can release this crate as 1.0 [near/near-account-id-rs#5](https://github.com/near/near-account-id-rs/issues/5) and extract it from the nearcore 0.x releases.
> 
> There are more such 1.0 crates will appear:
> 
> * https://github.com/near/near-gas-rs
> * https://github.com/near/near-token-rs
> 
> This all is part of a bigger initiative to finally make the tooling landscape easy for consumption in on-chain and off-chain apps

2023-10-27 20:19 UTC, closed without merging