[protocol_change] Decrease function call base cost
near/nearcore pull request #10943
Opened 2024-04-04 15:21 UTC by akashin

This PR decreases the function call base execution cost to 1TGas.
It is stacked on https://github.com/near/nearcore/pull/10941.

2024-04-04 15:26 UTC, akhi3030 approved these changes

2024-04-04 16:07 UTC, Ekleog-NEAR reviewed
I think we need to change more gas costs than just this one in order to avoid a situation later where we’ll want to raise the per-byte cost significantly and not be able to.

To do that, I think we should:
- Reduce execution costs as decided in the meeting, because while it’s the riskiest change (with the undercharging risk) it’s also the one we expect to get most benefit from on congested shards
- Reduce send costs to like 100-500Ggas, because while we’re unsure about execution costs, send costs should definitely be much lower than that — and reducing them might help us decongest the shards by the transactions sent by other accounts on the same shard
- Increase per-byte costs, so that the maximal size of a 4MB contract stays at the same cost. This is because we likely already undercharge for large contracts, and if we don’t increase the per-byte costs at the same time as we decrease the base costs, we won’t be able to increase it later

With these changes, we’ll lower the affine function by keeping the same end and lowering the "0 size" case. The contracts we’re interested in optimizing for are on the lower end of the size spectrum, so we should reap most of the benefits, while avoiding the risk of significant undercharging for large contracts

cc @bowenwang1996 if you have an opinion on this plan?

I likely won’t have the time to do a second round of review today, so I’ll let you land based on Akhi’s approval if the discussion stabilizes, and come back tomorrow otherwise :)

2024-04-04 16:50 UTC, Ekleog-NEAR commented
This would result in the following numbers:
- Function call base send: 2_319_861_500_000 -> 200_000_000_000
- Function call base exec: 2_319_861_500_000 -> 1_000_000_000_000
- Function call per-byte send: 2_235_934 -> 2_741_348
- Function call per-byte exec: 2_235_934 -> 2_550_613

This (rounds-down) the total cost for a 4_194_304 bytes contract (our `max_contract_size`) to the same value as before

2024-04-04 17:12 UTC, Ekleog-NEAR commented
Erratum: I used the wrong costs, as [pointed out by Bowen on Zulip](https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/moar.20congestion/near/431360761):

The corrected estimations are:
- Function call base send: 2_319_861_500_000 -> 200_000_000_000 (estimator-provided value: ~10_000_000)
- Function call base exec: 2_319_861_500_000 -> 1_000_000_000_000 (estimator-provided value: 108_726_617_500)
- Contract loading per-byte: 216_750 -> 1_036_843 (estimator-provided value: 5_500_000)

2024-04-05 12:18 UTC, akashin commented
I've updated the costs to suggested values - this PR should be ready for testing on mocknet.

2024-04-05 12:34 UTC, Ekleog-NEAR approved these changes
LGTM! :)

2024-04-05 12:34 UTC, Ekleog-NEAR commented on core/parameters/src/config_store.rs
> +            if *protocol_version >= DecreaseFunctionCallBaseCost.protocol_version() {
Nit: add a `// TODO` referencing https://github.com/near/nearcore/issues/10955

2024-04-05 13:49 UTC, bowenwang1996 requested changes
Copy paste what I wrote on zulip: I thought the discussion [here](https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/moar.20congestion/near/431364068) refers to a later change down the line. The issue is that if we do this change as is, then we don't gain much in terms of improving receipt throughput because when a function call receipt is executed, we charge both exec cost and wasm_contract_loading_bytes. I suggest we go with changing only exec cost now and do other changes after we have a more comprehensive understanding of the performance characteristics of runtime

2024-04-05 15:04 UTC, Ekleog-NEAR commented
Copying here the results of the discussion from zulip: it’s probably best to go with option 3 described there, aka:
- Function call base send: 2_319_861_500_000 -> 200_000_000_000 (estimator-provided value: ~10_000_000)
- Function call base exec: 2_319_861_500_000 -> 780_000_000_000 (estimator-provided value: 108_726_617_500)
- Contract loading per-byte: 216_750 -> 1_089_295 (estimator-provided value: 5_500_000)

This gets 300kB contracts down to 1.1Tgas exec cost (the same value as just lowering function call base exec cost to 1Tgas), while still keeping 4MB contracts at the same cost as before

2024-04-05 16:09 UTC, bowenwang1996 approved these changes

2024-04-08 13:48 UTC, merged