fix(epoch_sync) - fix unintential epoch sync feature inclusion
near/nearcore pull request #11158
Opened 2024-04-25 14:54 UTC by wacban

The epoch sync was getting enabled when using wide build commands that included the epoch sync tool. 

I'm moving the conditional enablement from Cargo.toml to the rust files.

2024-04-25 14:56 UTC, akhi3030 approved these changes
I don't have sufficient understanding of how features work to properly review this.  But if the original reported problem is addressed, I am happy to approve it.

2024-04-25 15:01 UTC, Ekleog-NEAR requested changes
This doesn’t actually do what you want it to do. The `#![cfg]` lines have as an impact to not compile if the `new_epoch_sync` feature flag is not passed to the `epoch-sync` crate.

However, that crate does not actually expose this feature flag in its Cargo.toml, meaning that it becomes essentially impossible to compile the code, and the crate just became empty.

If the `epoch-sync` library is currently not used anywhere in our code then tests will pass, but the whole library just becomes dead code with this change.

Unfortunately, moving the check to rust will require one of:
- Making this feature a configuration option (probably the best option)
- Add a feature flag in all crates that require it (eg. the `epoch-sync` crate), and enable nearcore’s new_epoch_sync feature flag if this feature flag is enabled (see feature flag dependencies in the cargo manifest book)

2024-04-26 07:21 UTC, wacban commented
Good point @Ekleog-NEAR! Can you have another look? I made it so that neard/new_epoch_sync enables the new_epoch_sync in the epoch sync tool. 

verified:
* cargo run -p neard --features new_epoch_sync -- epoch-sync -h 
  * works
* cargo run -p neard -- -h 
  * the epoch sync subcommand is not present in the list

2024-04-26 07:22 UTC, Ekleog-NEAR approved these changes
r+ with a nit: the new `new_epoch_sync` feature should also automatically enable nearcore's `new_epoch_sync` feature, else `cargo build -p near-epoch-sync-tool` will fail :)

Thank you for having looked into this!

2024-04-26 11:20 UTC, Ekleog-NEAR approved these changes
LGTM :)

2024-04-26 11:54 UTC, merged