feat(mirror): add a transactions per second option
near/nearcore pull request #11357
Opened 2024-05-21 06:01 UTC by marcelo-gonzalez

This adds an option to control the traffic load by specifying how many transactions per second to send. This still sends the same set of transactions, but iterates through them and selects an amount to send that will get us close to the tps number we're looking for, rather than just sending a whole block's worth at a time

This PR is complicated by the way things work in this mirror tool currently, and it would be great to find a way to simplify things and delete code in the future. But for now sadly things have to get even a little more complicated to implement this, since there's some stuff that could go wrong with the way nonces are handled

2024-05-21 18:15 UTC, tayfunelmas commented on tools/mirror/src/lib.rs
> +enum TxBookmark {
can you add comments to the structs and fields about what they represent and/or how they are used?

2024-05-21 18:16 UTC, tayfunelmas commented on tools/mirror/src/lib.rs
> +fn get_first_accounts_created(db: &DB) -> anyhow::Result<bool> {
what does creating first accounts mean? is it about the initial setup? can you add comments to clarify these?

2024-05-21 18:21 UTC, tayfunelmas commented on tools/mirror/src/chain_tracker.rs
> +                    batch_count: 1,
I think comment for batch_count would help, I do not understand why the batch is 1 here, do you mean everything within a second will be sent together or something else?

2024-05-21 23:16 UTC, tayfunelmas requested changes
I put some comments about adding comments to the code because it is hard to parse what is going on. In addition, can you explain the design shortly in the PR description?

2024-05-21 23:16 UTC, tayfunelmas commented on tools/mirror/src/lib.rs
> +        .get_cf(db.cf_handle(DBCol::Misc.name()).unwrap(), "traffic_checkpoint")?
can you define these constants (eg. traffic_checkpoint and last_source_height at the top of the file as the DB keys and explain what they are supposed to contain?

2024-06-05 19:40 UTC, marcelo-gonzalez commented
going to finish testing this, and I think there might be some extra bugs in here that need to be fixed, then i'll add all these comments, since I agree it is very light on explanations here...

2025-03-19 13:54 UTC, closed without merging