[ft-benchmark] add note about db-sending scripts to README
near/nearcore pull request #11616
Opened 2024-06-19 11:24 UTC by MCJOHN974

2024-06-19 11:56 UTC, akashin requested changes

2024-06-19 11:56 UTC, akashin commented on benchmarks/continous/db/README.md
> +# Adding results of you benchmark automatically.
Nit: Remove dot in the end of the heading for consistency

2024-06-19 11:56 UTC, akashin commented on benchmarks/continous/db/README.md
This is the documentation for the database for the benchmark, not the benchmark itself, so I think we need to move these instructions elsewhere. I see two options:
1. Add them to our outline document: https://docs.nearone.org/doc/crt-benchmark-8IpRzRV7C5/ - simpler short-term, but not as discoverable
2. Create a new document under Workflows section of developer documentation (https://near.github.io/nearcore/practices/workflows/index.html, https://github.com/near/nearcore/tree/master/docs/practices/workflows) - a proper place for the long-term

2024-06-19 12:27 UTC, MCJOHN974 commented on benchmarks/continous/db/README.md
What about just moving it to `benchmarks/continous/`? (And also move all ft-benchmark related scripts there)

2024-06-21 14:35 UTC, MCJOHN974 commented
https://github.com/near/nearcore/pull/11644 will replace it

2024-06-21 14:35 UTC, closed without merging