Update otel-traces documentation
near/nearcore pull request #11779
Opened 2024-07-12 18:43 UTC by jancionear

Mention that the `rust_log` level has to be higher than the `opentelemetry` level.
I tried to setup a node where `log_config.json` looked like this:
```json
{ "opentelemetry": "info,runtime=debug,vm=debug"}
```

But it didn't work because the `rust_log` log level was too low.
Setting it to:
```json
{ "opentelemetry": "info,runtime=debug,vm=debug", "rust_log": "info,runtime=debug,vm=debug" }
```
fixed the problem.

Refs: [zulip conversation](https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/Running.20Kent's.20workload.20on.20statelessnet/near/451039992)

2024-07-15 18:12 UTC, nagisa requested changes
FWIW this sounds like a bug or a misunderstanding -- I definitely didn't need to do anything like this in my use of tracing and it is also weird that doing so would be necessary (dumping a bucketloads of log lines into journal only to enable tracing seems counter-productive too.)

All that said, I don't think it makes sense to document buggy or unintended behaviour over fixing the cause in the first place.

2024-08-01 12:48 UTC, tayfunelmas approved these changes

2024-08-01 12:49 UTC, tayfunelmas commented
Actually just saw the comment from @nagisa, do you plan to fix the issue or want to go forward with the documentation change?

2024-08-01 12:57 UTC, jancionear commented
Ah sorry I forgot about this PR. I opened it because we had to enable debug logs on a statelessnet node to get the traces. I know very little about OpenTelemertry so it's hard for me to say if it should be required or not, but Simonas said that it shouldn't, so I'll close the PR.
It'd be nice to investigate why the traces weren't enabled.

2024-08-01 12:57 UTC, closed without merging