feat(contract-distribution): Filter out contract accesses that are newly-deployed and not present
near/nearcore pull request #12350
Opened 2024-10-30 18:06 UTC by tayfunelmas

Currently function call may fail if code does not exist (eg. code-hash of the account is either default-hash or wrong). In this case, the failure of executing the function comes later, so we already record that the missing contract is called.

To fix this, there are two approaches:
1) Identify that there is ContractNotPresent error when executing the function and not record the call if that happens.
2) When finalizing the `ContractStorage`, not include the code-hashes that a) are newly-deployed and 2) do not exist in the storage.

We take the second approach here, since the first approach led to non-clear code and prone to errors later as the code changes. The second approach introduces a storage read for the accesses, but we are already doing these reads in the current protocol (since we record the read of the contract code).

We update some unittests based on this change and add a new unittest for calling a missing contract (which fails without this change).

We also remove an optimization from the witness producer to exclude the deployments from accesses, since we are doing it in the `ContractStorage` now.

2024-10-30 18:06 UTC, tayfunelmas commented on chain/client/src/stateless_validation/state_witness_producer.rs
> -        let predeployed_contract_accesses =
this is not needed anymore, since we are doing the filtering in the `ContractStorage::finalize` now.

2024-10-30 18:40 UTC, pugachAG requested changes
doesn't this mean that we have to read all contract accesses from storage now? right now that happens rarely since most of them are served from the compiled contract cache

2024-10-30 18:53 UTC, tayfunelmas commented
> doesn't this mean that we have to read all contract accesses from storage now? right now that happens rarely since most of them are served from the compiled contract cache

Even though they are served from the compiled contract cache, we still read them from the storage here: https://github.com/near/nearcore/blob/8e30ccdd425ecbbeeec8d96bfc9a7e02bc35c2d3/core/store/src/trie/mod.rs#L1615

because we need to include them (along with the internal nodes in trie) in the witness. let me know if I miss anything.

The compiled contract caches still optimizes the latency since we do not need to re-compiled the code.

The ideal setup would be some kind of `contains` method to check if key exists without returning the data but could not find it yet.

Another option is to not call `record_call` function if the executing the function returns code-not-present error (https://github.com/near/nearcore/blob/8e30ccdd425ecbbeeec8d96bfc9a7e02bc35c2d3/runtime/runtime/src/actions.rs#L122), which currently happens after the `record_call` call when executing the action (https://github.com/near/nearcore/blob/8e30ccdd425ecbbeeec8d96bfc9a7e02bc35c2d3/runtime/runtime/src/actions.rs#L216), but I found that approach brittle.

2024-11-01 13:19 UTC, tayfunelmas commented on core/store/src/trie/mod.rs
> -        let key = key.to_vec();
code for `get_optimized_ref_no_side_effects` is extracted from here.

2024-11-01 15:25 UTC, merged