add test to cover stress.py fails
near/nearcore pull request #3089
Opened 2020-08-05 23:26 UTC by pmnoxx

Add a new test, which should. detect failures fixed in https://github.com/nearprotocol/nearcore/pull/3036

2020-08-10 21:45 UTC, SkidanovAlex commented on pytest/tests/sanity/proxy_loose_block_messages.py
> +            if height2producer[h] == NODES - 1 and fr == NODES - 1 and to < (NODES - 1) / 2:
We want to block the first occurrence of `(h, fr, to)`.

2020-08-11 02:42 UTC, SkidanovAlex commented on pytest/xx.py
> +from multiprocessing import Process, Value, Array
was this intended to be added to the PR?

2020-08-11 02:44 UTC, SkidanovAlex commented on pytest/tests/sanity/proxy_loose_block_messages.py
> +            if h > self.handler_state.value:
is `handler_state.value` used anywhere?

2020-08-11 02:44 UTC, SkidanovAlex commented on pytest/tests/sanity/proxy_loose_block_messages.py
> +            if h % NODES == NODES - 1 and tpl not in ignored_messages:
This drops it to all the recipients, not just half of them, right?

2021-07-01 18:42 UTC, bowenwang1996 commented
@pmnoxx @SkidanovAlex what is the status of this PR?

2021-11-12 03:42 UTC, pmnoxx commented
https://nayduck.near.org/#/run/2202

2021-11-12 14:02 UTC, mm-near requested changes

2021-11-12 14:02 UTC, mm-near commented on pytest/tests/sanity/proxy_loose_block_messages.py
> +
can you explain what this test does?

2021-11-16 06:43 UTC, closed without merging