refactor(indexer): Attach local receipt to chunk. Remove local_receipts field from StreamerMessage
near/nearcore pull request #3513
Opened 2020-10-21 14:46 UTC by khorolets

Closes #3497

2020-10-21 20:55 UTC, frol requested changes

2020-10-21 20:55 UTC, frol commented on chain/indexer/src/streamer/streamer.rs
> +        let mut chunk_receipts = local_receipts.clone();
You don't need to accumulate and clone the local receipts. Just prepend the result of `convert_transactions_sir_into_local_receipts` to the non-local receipts (let's rename the field while we unpacking:

```rust
let views::ChunkView { transactions, author, header, receipts: non_local_receipts } = chunk;

let local_receipts = convert_transactions_sir_into_local_receipts(...).await?;
let mut receipts = local_receipts;
receipts.extend(non_local_receipts);
```

2020-10-22 09:20 UTC, khorolets commented
@frol please have a look at clippy warning

```
warning: module has the same name as its containing module
 --> chain/indexer/src/streamer/mod.rs:7:1
  |
7 | mod streamer;
  | ^^^^^^^^^^^^^
  |
  = note: `#[warn(clippy::module_inception)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#module_inception
```

I guess we should rename the `streamer/streamer.rs`. I can suggest 
* stream
* stream_message
* handler
* streamer_message

2020-10-22 13:15 UTC, frol approved these changes
Feel free to merge without my further review.

2020-10-22 13:15 UTC, frol commented on chain/indexer/src/streamer/fetchers.rs
> +}
Let's have them in `types.rs`

2020-10-22 13:52 UTC, frol commented on chain/indexer/src/streamer/fetchers.rs
> +use crate::streamer::errors::FailedToFetchData;
```suggestion
use super::INDEXER;
use super::errors::FailedToFetchData;
use super::types::{ExecutionOutcomesWithReceipts, IndexerExecutionOutcomeWithReceipt};
```

2020-10-22 14:47 UTC, merged