Move to cost taking IO into account.
near/nearcore pull request #3818
Opened 2021-01-19 12:43 UTC by olonho

2021-01-19 20:47 UTC, bowenwang1996 commented on core/primitives/src/version.rs
> +pub const PROTOCOL_VERSION: ProtocolVersion = 48;
what is the new feature? We update nightly protocol version only if we change a feature or add a new feature

2021-01-20 00:39 UTC, evgenykuzyakov requested changes
Changing default will create an issue and not upgrade the existing protocol. There is a PR with a proper fix using a new experimental feature that does live migration: https://github.com/near/nearcore/pull/3653

But we also have a breaking change with the gas price computation based on the total prepaid gas amount, but this PR doesn't change it.

2021-01-20 00:39 UTC, evgenykuzyakov commented on runtime/runtime-params-estimator/Cargo.toml
> +required = ["costs_counting", "near-vm-runner/no_cpu_compatibility_checks", "no_cache"]
Still don't understand why we don't run single thread rocksdb.

2021-07-01 18:49 UTC, bowenwang1996 commented
@olonho do we still want to keep this PR?

2021-07-08 12:25 UTC, matklad commented
We definitely want to wrap this work up, as the current situation is self-contradictory: #4474. The current params estimator doesn't actually the costs we currently use. Not sure if its better to revive this PR or create a new one, that's up to @olonho

2021-12-08 17:24 UTC, closed without merging

2021-12-08 17:25 UTC, olonho commented
No longer relevant.