fix(runtime): clean up runtime traps, remove unused ones, map wasmer 0.x trap to near error
near/nearcore pull request #3822
Opened 2021-01-20 02:53 UTC by ailisp

Some near vm errors were never constructed. Drop some of them, and construct remaining of them when wasmer 0.x trap corresponding traps

Test Plan
---------
near vm tests in CI

2021-01-20 18:45 UTC, evgenykuzyakov requested changes
This will break consensus. You can't change errors without a protocol upgrade, because they have to be deterministic

2021-01-20 18:58 UTC, ailisp commented
> This will break consensus. You can't change errors without a protocol upgrade, because they have to be deterministic

Error changes, however it doesn't break consensus:
- when there's no error, same behavior
- when there's error, both this pr and old one would give error, but some WasmerUnknownError becomes more specialized errors, no state change is applied
- there's no case when it was error that would succeed now or it was successful that would fail now
So I don't think a protocol upgrade is necessary?

2021-01-21 01:05 UTC, evgenykuzyakov commented
> when there's error, both this pr and old one would give error, but some WasmerUnknownError becomes more specialized errors, no state change is applied.

I think we merklize errors in `ExecutionOutcome`

2021-01-21 17:58 UTC, ailisp commented
I see, it's problematic then, and wasmer 1.0 runner must under another
protocol version/feature for same reason

On Wed, Jan 20, 2021 at 5:05 PM Evgeny Kuzyakov <notifications@github.com>
wrote:

> when there's error, both this pr and old one would give error, but some
> WasmerUnknownError becomes more specialized errors, no state change is
> applied.
>
> I think we merklize errors in ExecutionOutcome
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/near/nearcore/pull/3822#issuecomment-764140049>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADFFFCF5BM6YXULOLEGDCRLS254UZANCNFSM4WJ7WXLA>
> .
>

2021-04-15 17:38 UTC, closed without merging