refactor: reduce the number of deps for public libraries
near/nearcore pull request #4183
Opened 2021-04-01 09:56 UTC by matklad

primitives-core is an API crate, so all of its deps become deps of
consumers of the library. This makes deps significantly more costly.

For derive-more in particular, it seems like it is not used that
heavily.

2021-04-01 09:57 UTC, matklad commented
@frol this is more of a suggestion PR: I don't have enough experience to understand whether we want to do this or not. I think you are the better person to make a judgement call here :)

2021-04-01 22:55 UTC, bowenwang1996 approved these changes
I think this PR makes sense

2021-04-02 09:59 UTC, frol requested changes
I am only fine with this change if we measure the improvement and enforce it. My measurement is that with `derive_more` I need to read less code, and I don't believe at this point that you can notice any improvement with the proposed change. As to the enforcement, the next time someone goes to this file, they potentially will introduce `derive_more`, and we will be back to square one.

I think the problem you raised needs to be addressed systematically, and make sure that our crates granularity is correct before we try to save some bits.

2021-04-02 10:44 UTC, matklad commented
> our crates granularity is correct before we try to save some bits.

That's a great point, agree that this is premature optimization at this point, closing!

> measure the improvement

I've tried `cd core/primitives-core && t cargo build --lib -j 1`, the results look like this:

```rust
# With derive more
real 32.10s
cpu  33.02s (30.78s user + 2.24s sys)
rss  452.62mb

# Without derive more
real 28.18s
cpu  28.93s (26.89s user + 2.04s sys)
rss  392.70mb
```

So that's 4 seconds absolute / 14 % relative difference in *the worst-case* (from scratch debug build). `derive-more` seems to be among the bigger ones in this corener of the crate graps:

![image](https://user-images.githubusercontent.com/1711539/113409060-2beb3600-93b9-11eb-8215-487e86034cc1.png)

(`env RUSTC_BOOTSTRAP=1 cargo build --lib -j 1 -Ztimings`)

> and enforce it

The enforcement that works well for rust-analayzer is three-fold:

* dependency stance [is documented](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/style.md#cratesio-dependencies)
* by the time folks get review permissions, they generally know that we don't do deps
* once in a while I read Cargo.lock to see if I need to raise some issues for our dependencies :)

2021-04-02 10:44 UTC, closed without merging

2021-04-02 11:03 UTC, matklad commented
Forgot to mention one more thing: 

>My measurement is that with derive_more I need to read less code

I personally feel the opposite: with derive_more, I need to read *more* code. It's not immediately obvious if it implements `AsRef<[u8]>` or `AsRef<[u8; 32]>`, and if I "goto definition", than I land into proc macro, which is not too transparent.

2021-04-02 12:28 UTC, frol commented
Great points! I would love to see those measures applied. Currently, we only use `cargo-deny` to protect us from too many duplicate dependencies (we [cannot avoid them completely since](https://github.com/near/nearcore/blob/master/deny.toml) we pull out quite massive third-party dependencies like wasmer, wasmtime, evm, and various crypto implementations)