Cap maximum gas price
near/nearcore pull request #4308
Opened 2021-05-20 00:29 UTC by Longarithm

2021-05-20 23:24 UTC, bowenwang1996 requested changes
Please add a test that asserts the gas price does not exceed maximum gas price even when there is congestion.

2021-05-21 21:37 UTC, Longarithm commented
Added new tests and moved creation of congestion to a separate function

2021-05-24 18:58 UTC, bowenwang1996 approved these changes
Well done!

2021-05-24 18:58 UTC, bowenwang1996 commented on chain/client/tests/process_blocks.rs
> +fn create_env_with_congestion(
Nice

2021-05-24 18:58 UTC, bowenwang1996 commented on chain/client/tests/process_blocks.rs
> +                return true;
Please also assert that congestion actually happens. You can do this by asserting that gas usage is at least as large as gas limit.

2021-05-24 23:31 UTC, merged