fix: Dont broadcast empty `SyncData`
near/nearcore pull request #5602
Opened 2021-12-03 04:53 UTC by pmnoxx

There was one case, where we could broadcast an empty list of edges inside `add_verified_edges_to_routing_table`.
Let's fix that.

2021-12-09 10:16 UTC, mm-near requested changes

2021-12-09 10:16 UTC, mm-near commented on chain/network/src/peer_manager/peer_manager_actor.rs
> +                    if broadcast_edges
when we do fix like this - let's make sure that we add a test that covers it.

2022-01-04 18:13 UTC, pmnoxx commented
```
@bowenwang1996 @mm-near: chain/network/
```
@bowenwang1996 @mm-near Can you take a look?

2022-01-11 19:35 UTC, pmnoxx commented
```
@bowenwang1996 @mm-near: chain/network/
```
@bowenwang1996 @mm-near Can you take a look?

2022-01-18 22:31 UTC, pmnoxx commented
```
@bowenwang1996 @mm-near: chain/network/
```
@bowenwang1996 @mm-near Can you take a look?

2022-03-07 17:36 UTC, closed without merging