re: Improve `Cargo.toml` in `near-rate-limiter`
near/nearcore pull request #5727
Opened 2021-12-09 03:14 UTC by pmnoxx

Authors section was missing in  `near-rate-limiter`  and also we should upgrade edition to 2021.

2021-12-23 10:39 UTC, miraclx reviewed
this is already on master:

https://github.com/near/nearcore/blob/24775089d61528c41b6a6d57ef5c0bde885941b0/utils/near-rate-limiter/Cargo.toml#L1-L8

2022-01-04 18:13 UTC, pmnoxx commented
```
@mm-near: utils
```
@mm-near Can you take a look?

2022-01-11 19:35 UTC, pmnoxx commented
```
@mm-near: utils
```
@mm-near Can you take a look?

2022-01-13 20:42 UTC, mm-near requested changes

2022-01-14 18:30 UTC, closed without merging