Remove `From<Vec<u8>>` for `CryptoHash`
near/nearcore pull request #5784
Opened 2021-12-12 08:36 UTC by pmnoxx

We can remove `impl TryFrom<Vec<u8>>` for `CryptoHash`
This will remove extra memory allocations and make code shorter.

2021-12-12 18:11 UTC, mina86 requested changes

2021-12-12 18:49 UTC, pmnoxx commented on core/primitives-core/src/hash.rs
>      }
Yes, https://github.com/near/nearcore/pull/5788

2021-12-12 18:50 UTC, pmnoxx commented on core/primitives-core/src/hash.rs
>      }
@mina86 Thanks, I like it, it's even better xD

2021-12-12 18:53 UTC, mina86 approved these changes

2021-12-15 12:46 UTC, mm-near approved these changes

2021-12-21 04:28 UTC, pmnoxx commented
```
@mzhangmzz: /core/store/src/trie
```
@mzhangmzz Can you take a look?

2021-12-21 12:52 UTC, Longarithm approved these changes

2021-12-21 15:11 UTC, merged