neard: warn when running unsupported build on mainnet or testnet
near/nearcore pull request #5890
Opened 2021-12-18 00:56 UTC by mina86

Building via `cargo build` or even `cargo build --release` produces
insufficiently-optimised build.  The recommended way to create an
executable to run in production is `make release` which enables LTO.

There is, however, no mechanism which prevents users from or warns
them about running badly-optimised nodes.

Add a mechanism which will print warnings to the logs when trying to
initialise or run a mainnet or testnet log using an executable which
was not built via `make release` or `make nightly-release`
respectively.

2021-12-18 01:10 UTC, pmnoxx commented
@mina86 SGTM. I think it's a great if we can eliminate user error as one source of possible mistakes.

2021-12-21 01:34 UTC, bowenwang1996 requested changes

2021-12-21 01:34 UTC, bowenwang1996 commented on neard/src/cli.rs
> +    let is_testnet_build = is_release_build && is_nightly_build;
No, testnet only runs stable protocols

2021-12-21 02:13 UTC, mina86 commented on neard/src/cli.rs
> +        option_env!("NEAR_RELEASE_BUILD").map(|value| value == "yes").unwrap_or(false);
RUSTFLAGS variable is read by cargo to customise options passed to the compiler but it’s cleared when rustc is actually executed.

2021-12-22 11:39 UTC, mina86 commented
@mm-near, friendly ping.

2021-12-22 20:41 UTC, pmnoxx commented on neard/src/cli.rs
> +        option_env!("NEAR_RELEASE_BUILD").map(|value| value == "yes").unwrap_or(false);
@mina86 Yes, I just checked. Unfortunately, those variables are not set. 
@matklad I wish there was a way to get `OPT_LEVEL` env variable, from the time the compilation was done.

2021-12-22 20:43 UTC, pmnoxx approved these changes
LGTM,

Though probably magic keyword is not needed, rather than something like

`NEAR_BUILD_TARGET=release` would be enough.

2021-12-22 21:36 UTC, mina86 commented on neard/src/cli.rs
> +        option_env!("NEAR_RELEASE_BUILD").map(|value| value == "yes").unwrap_or(false);
There shouldn’t really be any reason to have conditional compilation based on optimisation level so general sentiment is to not have that ability in Rust.

2021-12-28 18:21 UTC, bowenwang1996 approved these changes

2021-12-28 20:55 UTC, merged