re: Reformat `Cargo.toml` for `near-network` related packages
near/nearcore pull request #5966
Opened 2021-12-23 18:45 UTC by pmnoxx

Let's format `Cargo.toml` files properly.

2021-12-23 18:45 UTC, pmnoxx commented
```
@mm-near: /chain/network-primitives/ /chain/network/ /utils
```
@mm-near Can you take a look?

2022-01-13 11:50 UTC, mm-near requested changes

2022-01-13 11:50 UTC, mm-near commented on chain/network-primitives/Cargo.toml
> +    "Piotr Mikulski <piotr@near.org>"
Not sure about NEAR - but normally you'd not mention your name directly as the owner of the packet (this becomes stale too often)

2022-01-17 14:30 UTC, mm-near approved these changes

2022-01-18 18:13 UTC, merged