feat: cache chunk nodes
near/nearcore pull request #6292
Opened 2022-02-15 11:25 UTC by Longarithm

TODO: describe the feature

2022-02-15 14:36 UTC, mm-near requested changes

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +    /// Value is not presented.
s/presented/present

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +    /// Value is presented in the shard cache.
s/presented/present

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +    /// Value is presented in the chunk cache.
same as above

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +pub enum TrieNodeRetrievalCost {
comment

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +    shard_cache: LruCache<CryptoHash, Vec<u8>>,
later we should check how much faster would it be to use Arc<Vec<u8>> here (and 1 line below)

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +                    self.chunk_cache.insert(key.clone(), value);
comment what we're doing here

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +            if self.chunk_cache.contains_key(&key) {
comments..

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +        guard.cache_state = TrieCacheState::CachingShard;
consider adding "clear" method to TrieCache and calling it from here

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +
and now switch to CachingShard - and check that you're being charged on "get"

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +        guard.cache_state = state;
and where do we have the code that "moves" stuff from chunk_cache to shard_cache when state changes ?

2022-02-15 14:36 UTC, mm-near commented on core/store/src/trie/trie_storage.rs
> +    }
we might have a nasty bug here...

trie.push(key, small_value)
assert trie.get(key) == small_value
trie.push(key, large_value) 
assert trie.get(key) == ??? // I think that current code will return small_value if "large_value" is > TRIE_MAX_SHARD_CACHE_SIZE

2022-02-15 15:31 UTC, matklad commented
Hm, still not very happy with the shape of code here. Let me try to summarize the issues: 

* Our goal here is to implement a non-transparent caching -- a cache which effectively allows reading "hit rate" which itself affects the protocol via costs
* This is a tricky, stateful business: we have parts of code where we do want to meter cache access, and parts of code where we don't. We definitely do not want non-metered parts to affect the metered ones. 
* The fundamental owned of all the data is the `NightshadeRuntime` struct. In particular, `tries: ShardTries,` is the owner of trie caches.
* The caching logic we want to add is tricky: we can't just *layer* it on top of existing cache, we want to modify the caching logic.
  * In particular, while we *can* just layer a second cache on top, it'll lead to caching the data twice, and that's prohibitive amount of memory. We do want to "move" the cached entries between transparent and opaque caches. 
* `NightshadeRuntime` is shared across the threads. Most of the code intreacts with `NightshadeRuntime` via `RuntimeAdapter` trait, which uses `&self` (shared access everywhere). Essentially, we have one clinet and a bunch of view clients, and they all concurrently access the same `NightshadeRuntime` object, which requires `NightshadeRuntime` to be thread safe.
* It can be argued that maybe each client should have its own independent copy of `NightshadeRuntime` so that they can use single-threaded caches, and avoid synchronization, but this is a huuge change to architecture of the whole thing. 

Which together brings us to the main tech-debt problem with the implementation: the "metering state" toggle, `cache_state: TrieCacheState,` is stored in a `Sync` data structure and it is possible to *concurrently* toggle this state, which is obviously completely invalid. This not entirely theoretical concern -- in the past, we had a bug where concurrent view calls affected metering results for main client. 

<hr/>

A new thing I've realised recently is that, while `ShardTries` data structure needs to be thread-safe, as a part of `NightshadeRuntime`, the `Trie` and in particular `TrieStorage` don't need to be thread safe. In particular, the following diff works:

```diff
diff --git a/core/store/src/trie/trie_storage.rs b/core/store/src/trie/trie_storage.rs
index f302757f8..625b38265 100644
--- a/core/store/src/trie/trie_storage.rs
+++ b/core/store/src/trie/trie_storage.rs
@@ -196,15 +196,15 @@ impl TrieStorage for TrieCachingStorage {
 /// Trie increments it on every call to TrieStorage::retrieve_raw_bytes()
 #[derive(Default)]
 pub struct TouchedNodesCounter {
-    counter: AtomicU64,
+    counter: std::cell::Cell<u64>,
 }
 
 impl TouchedNodesCounter {
     pub fn increment(&self) {
-        self.counter.fetch_add(1, Ordering::SeqCst);
+        self.counter.set(self.counter.get() + 1);
     }
 
     pub fn get(&self) -> u64 {
-        self.counter.load(Ordering::SeqCst)
+        self.counter.get()
     }
 }
```

and makes the current code much less scary -- it makes it clear that it's impossible to touch nodes concurrently and actually actively prevents that via Rust's type system. (It might make sense to send that diff as a PR, as it improves today's code).

I think we can take advantage of this, and move the state-toggle from shared, thread-safe `TrieCache` to `CachingTrieStorage`, which doesn't need to be thread safe:

```diff
diff --git a/core/store/src/trie/mod.rs b/core/store/src/trie/mod.rs
index 556a85389..6a5477058 100644
--- a/core/store/src/trie/mod.rs
+++ b/core/store/src/trie/mod.rs
@@ -407,7 +407,6 @@ impl RawTrieNodeWithSize {
 
 pub struct Trie {
     pub(crate) storage: Box<dyn TrieStorage>,
-    pub counter: TouchedNodesCounter,
 }
 
 /// Stores reference count change for some key-value pair in DB.
diff --git a/core/store/src/trie/trie_storage.rs b/core/store/src/trie/trie_storage.rs
index f302757f8..737bbc6fb 100644
--- a/core/store/src/trie/trie_storage.rs
+++ b/core/store/src/trie/trie_storage.rs
@@ -135,6 +135,10 @@ pub struct TrieCachingStorage {
     pub(crate) store: Store,
     pub(crate) cache: TrieCache,
     pub(crate) shard_uid: ShardUId,
+
+    cache_state: std::cell::Cell<CacheState>,
+    chunk_cache: std::cell::RefCell<HashMap<CryptoHash, Vec<u8>>>,
+    touched_trie_nodes: std::cell::Cell<u64>,
 }
 
 impl TrieCachingStorage {
```

Differences from the current impl: 

* the `state` flag is stored in a `!Sync` data structure, so we don't have to worry about concurrent access
* touched_trie_nodes and chunk_cache are stored in the same data structure, which makes sense, as these two bits of state track the same info -- how much we should chare for trie ops

Similarities to the current impl:

* we still make use of interior mutability, just more bening, thread-unsafe version. In general, interior mutability is bad, and, if we make caching non-transparent, it is possible to argue that we should refactor call-sites to use `&mut Trie` or something. At the same time, "counting the number of times a read operation was issued" sounds like a defensible use of interior mutability. 
* accounting logic is moved from trie to trie_storage (in the PR, it is split between the two, in my suggestion, it is fully in the storage). I think this actually is a bug in both implementaitons -- if I understand the code correctly, we are going to use `TrieMemoryPartialStorage` when processing challenges, and that *should* contain the same cache metering logic. The current code (on mastre branch) doesn't have this problem, as accounting is done by the trie itself, not by the storage.

2022-02-15 16:01 UTC, matklad commented
:thinking: I've just realised that by moving entries between the two caches we distort the LRU picture, potentially making the cache less efficient.

2022-02-15 17:42 UTC, Longarithm commented
> I've just realised that by moving entries between the two caches we distort the LRU picture, potentially making the cache less efficient.

Yeah, this is a concern for us, because we want tx/receipt processing to be as fast as possible. The current implementation leaves the room for it.

> I think this actually is a bug in both implementaitons -- if I understand the code correctly, we are going to use TrieMemoryPartialStorage when processing challenges

The problem with `TrieMemoryPartialStorage` is valid. I think because we don't have challenges we can leave it as TODO for now.

The number of problems and discussions occurred with this change makes me think that it is not possible solve all them at once. I suggest to solve them sequentially, starting from this PR. What do you think? @matklad 

Another idea would be to store mutable reference to `TrieCachingStorage` in the **first** `TrieUpdate` which took `Rc<Trie>` and toggle cache state using this reference.

2022-02-16 09:49 UTC, matklad commented
> I suggest to solve them sequentially, starting from this PR. What do you think?

I am all for solving the problems sequentially, but, in this particular case, `pub fn set_state(&self, state: TrieCacheState) {`  (putting the state toggle into a shared data structure) doesn't feel like an incremental step towards the solution, if we are going to move that data out of that structure anyway. 

I'd see the incremental steps here as:

* Figure out who owns what in the end state
* Setup from https://github.com/near/nearcore/pull/6292#issuecomment-1040415712 makes most sense to me. This PRs setup really doesn't feel good to me. That's "architecture" concerns rather than "correctness" concerns, so, if people do feel that the ownership setup we have here is workable, we can ship it! 
* *If* the setup from that comment feels better, than incremental steps towards that:
  * changing TouchedTrieNodeCounter to use `Cell`, rather than `Atomic`
  * moving the counter from `Trie` to `TrieStorage` and adjusting the call-sites (I feel this might fail some tests for `RecordTrieStorage`, if we have them)
   * adding the "start counting/stop counting API" (this'll probably let us to assert that counter is zero when we start counting, to make sure we don't accidentally have "leftover" counts)
   * implementing the caching proper.

2022-03-11 10:37 UTC, Longarithm commented
Closing in favour of https://github.com/near/nearcore/pull/6414.

2022-03-11 10:37 UTC, closed without merging