pytest: fuzz: fix test not killing fuzz processes correctly
near/nearcore pull request #6298
Opened 2022-02-16 14:28 UTC by mina86

`subprocess.call(..., timeout=...)` will send KILL signal to the
process that has been spawned once the timeout passes but that may
leave its descendants still running.  To cover that case, handle
timeout ourselves by waiting and then killing the entire process tree.

2022-02-16 15:54 UTC, Ekleog approved these changes
Makes sense, I hadn't thought of `psutil`. An alternative would be to start the subprocess with `start_new_session=True` and then call `killpg(getpgid(proc.pid))` similar to what was done in nayduck#28.

2022-02-17 00:06 UTC, mina86 commented
`psutil` is what NayDuck was using when I took it over and I never changed it even though I think it is a more fragile method.  A test can escape process tree accidentally by doing a double fork while escaping a process group needs more deliberate action.  Nonetheless, so far we didn’t have issue with killing process tree so for now it’s probably good enough.

2022-02-17 10:38 UTC, Ekleog approved these changes

2022-02-17 14:26 UTC, mm-near requested changes

2022-02-17 14:26 UTC, mm-near commented on pytest/tests/fuzz.py
> +def run(directory: str, fuzz_target: str, timeout=typing.Optional[int]) -> int:
what is the unit for timeout ?

2022-02-17 14:26 UTC, mm-near commented on pytest/tests/fuzz.py
> +    running on NayDuck, returns None denoting no timeout.
what is the unit of the response?

2022-02-17 14:26 UTC, mm-near commented on pytest/tests/fuzz.py
> +def run(directory: str, fuzz_target: str, timeout=typing.Optional[int]) -> int:
also mention was it the response

2022-02-17 17:50 UTC, mm-near approved these changes

2022-02-17 19:03 UTC, merged