feat(params-estimator): Increase deployment cost
near/nearcore pull request #6397
Opened 2022-03-07 17:37 UTC by jakmeier

Set the deplyoment cost per byte to the maximum that still allows
deploying a 4MiB contract. This is to cover compilation costs.

2022-03-07 17:43 UTC, jakmeier commented
This is a protocol change. Since this is the first one I submit, I hope I got the technicalities for this right. Please let me know otherwise.

For now I updated the cost for version 52 but unless it is included in the next release, I will have to update this PR and create a new cost json file.

2022-03-08 10:53 UTC, mm-near requested changes

2022-03-08 10:53 UTC, mm-near commented on core/primitives/res/runtime_configs/52.json
> +        "execution": 64572944
I think that you might have to create version 53.. as 52 (AFAIK) was already pushed to testnet - but you can check with @mina86 who is doing that release.

2022-03-08 10:53 UTC, mm-near commented on integration-tests/src/tests/runtime/deployment.rs
> +        transaction_result.receipts_outcome[0].outcome.gas_burnt
how much gas does it burn now? how much is the headroom?

2022-03-08 16:24 UTC, Longarithm approved these changes

2022-03-08 19:21 UTC, jakmeier commented on runtime/near-test-contracts/src/lib.rs
> +    CONTRACT
good catch, removed the caching

2022-03-18 14:28 UTC, jakmeier commented
From my point of view, this is ready for final review.

I contacted everyone that I could identify to be affected by the change. And besides the test that I wrote already, I cannot think of anything that could be tested here.

If possible, I would like to include this in NEAR TestNet Release - 1.26.0-rc.1, scheduled for Wed, March 23.

2022-03-19 18:41 UTC, bowenwang1996 approved these changes

2022-03-21 10:41 UTC, mm-near approved these changes

2022-03-21 18:26 UTC, merged