Tool to grab snapshot of specific accounts for an epoch
near/nearcore pull request #6507
Opened 2022-03-29 14:50 UTC by EgorKulikov

@mzhangmzz please take a look

2022-03-31 11:15 UTC, mm-near requested changes

2022-03-31 11:15 UTC, mm-near commented on nearcore/src/runtime/snapshot_grabber.rs
> +pub struct SnapshotGrabber {
how do you use this tool?

I was expecting a stand-alone binary, which you can 'point' at the existing database, and pass some parameters (like which accounts to take etc).

2022-03-31 11:15 UTC, mm-near commented on nearcore/src/runtime/mod.rs
> +        #[cfg(feature = "snapshot_grabber")]
I'm surprised that we have to modify runtime code for this tool - I'd rather have this tool 'separate'

2022-12-15 15:12 UTC, akhi3030 commented
@EgorKulikov: this PR has not seen any activity in a long time. I am assuming is no longer being actively developed. I will close it. Please reopen when you are ready to work on it again.

2022-12-15 15:12 UTC, closed without merging