refactor: move the rest of block pre-processing logic to chain
near/nearcore pull request #6962
Opened 2022-06-03 14:10 UTC by matklad

2022-06-03 14:53 UTC, mzhangmzz commented on chain/chain/src/chain.rs
> +                .insert(pending_block, self.chain_update().into_saved_store_update());
I think you are right here! That's good. More code simplification.

2022-06-06 15:02 UTC, mm-near requested changes

2022-06-06 15:02 UTC, mm-near commented on chain/chain/src/chain.rs
> +    pub fn create_chunk_state_challenge(
due to code moves -- the git shows this file as 2k diff - very had to see which parts of the functions where 'just' moved vs modified.

2022-06-06 15:09 UTC, matklad commented on core/primitives/src/state_patch.rs
> +pub struct StatePatch {
wait, looks like I've messed up my git branching, this shouldn't be here yet at all..

2022-06-06 15:13 UTC, matklad commented on core/primitives/src/state_patch.rs
> +pub struct StatePatch {
Ah no, that's not a messed up branched, just accidentally commited code. The better version would be in a separate PR: https://github.com/near/nearcore/pull/6967

2022-06-06 15:19 UTC, matklad commented
```console
$ git diff --color-moved=dimmed-zebra HEAD~11 HEAD
```

Is the best I can come up with to review the code here :(

2022-06-08 10:22 UTC, mm-near approved these changes

2022-06-08 11:38 UTC, merged