Measure latency of network messages assuming all nodes have synchronized clocks
near/nearcore pull request #7050
Opened 2022-06-16 13:54 UTC by nikurt

This PR measures latency of all messages by adding a timestamp at the lowest level - at the protobuf level.

cc: @mm-near @mzhangmzz 
CPR-86

2022-06-16 13:56 UTC, nagisa commented
The overall approach makes sense to me, I had done something similar in the past. I’ve a question though: we have some beginnings of a distributed tracing framework, is there a reason why we couldn’t or shouldn’t utilize that for something like this?

2022-06-16 14:12 UTC, nagisa commented
> distributed tracing framework will let us see the network latency of a single trace, but doesn't support extracting network latency across all available traces and displaying them as a timeseries. In Grafana Tempo we can see timeseries of duration of traces filtered by span_type, etc. But network latency isn't represented as a span, but rather as a gap between spans.

Right, I wonder if we could somehow encode this as a key-value in the receiver’s span rather than as a gap between spans. I believe it should be possible to graph the value of a specific KV. But given the 2nd point, it seems like metrics are the way to go here anyway.

2022-06-17 07:06 UTC, pompon0 commented on chain/network/src/network_protocol/proto_conv.rs
> +        let tx_timestamp = SystemTime::now().duration_since(UNIX_EPOCH);
please don't make time-measurement encoding-dependent and move it to peer.rs.
Here you should just accept a timestamp as an argument.

2022-06-17 07:08 UTC, pompon0 commented on chain/network/src/network_protocol/network.proto
> +  google.protobuf.Timestamp tx_timestamp = 25;
Please document what this field represents.

2022-06-17 07:14 UTC, pompon0 commented on chain/network/src/network_protocol/proto_conv.rs
> +            tx_timestamp: MF::from_option(tx_timestamp.ok().map(|duration| {
please use https://github.com/near/nearcore/blob/2eec03616a924112da587a4da676c4883d1acd27/chain/network-primitives/src/time.rs#L66 
and convert it like this: https://github.com/near/nearcore/pull/7023/files#diff-2e879b433bc841c07dc50b3c7947ebf60988834054e0dd39b74e173b12b3c99d
(unfortunately this PR is not merged yet).

2022-06-17 07:15 UTC, pompon0 commented on chain/network/src/network_protocol/proto_conv.rs
> +            let latency = rx_timestamp.duration_since(tx_timestamp);
ditto, move it to peer_actor.rs

2022-06-17 07:19 UTC, pompon0 reviewed
In the context of the jira issue, aren't we more interested in latency of routed messages, rather than p2p messages?

2022-06-17 07:30 UTC, pompon0 commented on chain/network/src/network_protocol/network.proto
> +  google.protobuf.Timestamp tx_timestamp = 25;
"_timestamp" suffix is redundant with the field type. How about sth like "sent_at"?.

2022-06-20 09:04 UTC, nikurt commented
Please take another look. Moved the timestamp to the business logic layer and the change doesn't need a protocol upgrade.

2022-06-20 09:16 UTC, pompon0 commented on chain/network/src/peer_manager/peer_manager_actor.rs
> +                let duration = self.clock.now_utc().sub(created_at);
yes, that's the way I intended the clock to be used :+1: . Please also use self.clock when constructing the RoutedMessageV2.

2022-06-20 09:18 UTC, pompon0 requested changes
LGTM, I've left just a few comments to dedup logic that I also implemented in another PR, and to use the clock more consistently. Thanks.

2022-06-20 12:11 UTC, pompon0 commented on chain/network/src/network_protocol/proto_conv/peer_message.rs
> +                            tracing::warn!(target: "network", err=?err, "Malformed routed message created_at timestamp");
nit: I'd return an error if timestamp is not parseable: it is allowed to be missing, but not incorrect.

2022-06-20 12:16 UTC, pompon0 approved these changes
LG!

2022-06-20 19:22 UTC, nagisa approved these changes

2022-06-20 19:22 UTC, merged