store: use RocksDB’s iterate upper bound in prefix iterator
near/nearcore pull request #7111
Opened 2022-06-24 13:21 UTC by mina86

Rather than using `take_while` to stop iteration once we encounter
a key with a different prefix than requested, use RocksDB’s iterate
upper bound which may be used for effectively the same thing.

This adds `next_prefix` function which arguably is more complicated
than call to `take_while` but it makes the dynamic type returned from
`iter` and `iter_prefix` the same.  This will be helpful in upcoming
commit.

Issue: https://github.com/near/nearcore/issues/6583

2022-06-24 14:47 UTC, matklad commented on core/store/src/db.rs
> +    // If we’re hear, prefix consisted of \xff bytes.  There is no prefix that
```suggestion
    // If we’re here, prefix consisted of \xff bytes.  There is no prefix that
```

2022-06-27 03:52 UTC, mm-near requested changes

2022-06-27 03:52 UTC, mm-near commented on core/store/src/db.rs
> +fn next_prefix(prefix: &[u8]) -> Option<Vec<u8>> {
comment

2022-06-27 03:52 UTC, mm-near commented on core/store/src/db.rs
> +        }
if I understand correctly: 
next_prefix("a\xff\xff") would be "b\0\0", right ? 

shouldn't it be "b" ? 

can you add a unittest just for the next_prefix function ?

2022-06-27 14:46 UTC, mm-near approved these changes

2022-06-27 14:46 UTC, merged