store: refactor StoreUpdate
near/nearcore pull request #7219
Opened 2022-07-20 02:34 UTC by mina86

Use Deref magic to move all methods which queue new operations out of
StoreUpdate to DBTransaction and use generic arguments so that borrowed
slices as well as owned vector are accepted as arguments.  This avoids
owned vector from being cloned unnecessarily.

2022-07-20 10:20 UTC, matklad requested changes
This we should change:

* don't force key and value to be the same type, if we go with generics API
* use the same ownership strategy in `incerment_refcount`

Things we might consider changing:

* Use `Vec<>` over `Into`s
* Not using `Deref`

2022-07-20 10:20 UTC, matklad commented on core/store/src/lib.rs
> +}
Not a huge fan of using deref over just manually delegating. This priorities writer over reader: the write can just deref and get the API "for free", but the reader now has to piece the StoreUpdate API from StoreUpdate proper and the stuff it deref's to. Deref is a subtle and easy to miss thing. 

Additionally, delegation here would not be pure boilerplate, and can genuinely increase the abstraction level: In DbTx, we can implement core API, with `Vec<u8>` and `increse_refcount_by`, and in the StoreUpdate we can have convenience layer, where we use `Into<Vec<u8>>` and define `increase-refcount` in terms of `increase-refcount-by`. 

Do we actualy need both `DbTx` and `StoreUpdate`? Can we merge them into a single type? 

No super-strong opinion here.

2022-07-20 10:28 UTC, matklad commented
I also have a design question which prevented me from actually going and doing myself: 

If the end-goal here is to avoid copies, would accepting `Vec`s actually help? Like, it'll certainly help with the code as written, we are getting rid of some clones! 

However, this feels accidental. Looking at the WriteBatch API, there's a forced copy of data there, all methods take slices: 

https://github.com/facebook/rocksdb/blob/a0c63083d36b55d58afe635c44e5820324af05b4/include/rocksdb/write_batch.h

This makes perfect sense -- would be painful to pass a Rust vec to C++ DB. Looking at the fast_kv_store, it seems that it also wants to do a copy for write: 

https://github.com/near/fast-kv-store/blob/86dc2bdf248edc86063d3c4feec191370c454101/src/lib.rs#L325-L335


So perhaps the proper way to avoid copies here is to keep the current `&[u8]` API, but make sure we only `.to_vec()` in debug mode, so that we can implement no-overwrite protection?

2022-07-20 10:47 UTC, matklad commented
:thinking: yeah, I think I actually feels relatively strongly about the ^ point. 

It does seem that the *prefect* end-state interface would use `&[u8]`, with the database concatenating all the entries into some internal buffer with DB-specific structure, with some extra debug-only checks for overwrites via either iterating over DB WriteBatch itself, or via buffering operations into a `#[cfg(debug)]` buffer. 

And I think the actual perf win we'll be having here today is going to be really small, so I'd probably prioritise keeping the end-state API, and just documenting this like

```
// You might think that it'd be less copies to accept Vec's instead of slices here,
// but that's not necessary the case -- the's going to be a copy forced by the database anyway, see #7219 for discussion. 
struct StoreUpdate
```

2022-07-20 10:57 UTC, matklad commented
Let me cc @jakmeier who might have opinions about storage APIs

2022-07-20 14:24 UTC, jakmeier commented
First of all, I don't think I have too much to contribute here. Feel free to ignore my opinion. :)

But if you want to hear my opinion, personally, I would care more about code readability + maintainability than performance in this case. In-memory copies and some mallocs are probably close to negligible compared to the actual storage operation. (I would assume so until profiling shows evidence for the opposite.) 

Whether `Deref`-magic improves or worsens readability / maintainability can be debated, I don't have a strong opinion here.

With regards to `&[u8]` vs `impl Into<Vec<u8>>` vs `Vec<u8>`, probably slices and DB specific buffers would be best for micro-optimisation out of these three. But to push towards zero-copy, there are even better solutions. If I had to implement it, I'd take inspiration from [SKBs in the Linux kernel](http://vger.kernel.org/~davem/skb.html), basically pre-allocate buffers on the lowest layer and provide higher-up layers an interface to write to them, append to them, concatenate them etc. But please let's not do that, the code complexity is not worth it unless we are talking at least a couple of Gbit/s throughput. I just mention it to challenge the idea of a "perfect end-state" that we could predict today.

So I would actually tend towards `Vec<u8>`, it seems like the simplest interface.

2022-07-23 18:28 UTC, mina86 commented
OK, let’s pause it for now.  Part of the motivation for this was that I wanted to split StoreUpdate into StoreUpdate and ShardTriesUpdate and then have functions which one of those they take to just accept `&mut DBTransaction` (and hence the Deref).  However, it might be a bit more complex to split StoreUpdate the way I envisioned.

2022-07-23 18:28 UTC, closed without merging