Fix/rosetta rpc predecessor
near/nearcore pull request #7576
Opened 2022-09-07 09:23 UTC by firatNEAR

Based on tests from Coinbase some of the receipts did not have `predecessor_id` in their OperationMetadata. 

This PR fixes some receipts not having `predecessor_id`

2022-09-07 10:13 UTC, matklad reviewed
Could you elaborate a bit in the PR description why this is the right fix? 

Looking at the code, it seems that we generally have `receipts_in_block` map with recipts, and we add extra code to handle the case when the receipt isn't in that map. But that raises a question of *why* that happens? Perhaps we should fix something else to make sure all receipts are actually present in that map?

This is not a suggestion, I just genuinely don't understand why we are having this problem, and why this would be a complete and correct fix :)

2022-09-07 10:17 UTC, matklad commented
Oh, and can we add a test which actually demonstrates the change in the behavior here, so this doesn't regress in the future?

2022-09-21 17:14 UTC, frol requested changes
This PR won't solve the issue, see https://github.com/near/nearcore/issues/7654#issuecomment-1253990899

2022-10-17 13:58 UTC, frol commented
@firatNEAR  I’m not sure if this actually needs to be pushed forward. I feel having this incomplete solution where “predecessor id is not always available” is not helping much and only postpones potential problems for the users. Either you will need to push it till the very end like Indexer Framework does and ensure that predecessor id is not Option (Indexer Framework goes back to the parent blocks in the attempt to find the local delayed receipts, and if the parent is not found, it crashes), or remove this support completely in favor of #7704 (if predecessor id was only used to identify whether it was a fee transfer)

2022-10-18 10:27 UTC, frol approved these changes
After an offline discussion with @firatNEAR I realized that this PR will actually fix the case of the delayed receipts.

Two more corner cases will remain:

* local receipts
* delayed local receipts

Given that local receipts are only generated on transaction-to-receipt conversion (when sender-is-receiver, NEAR generates a local receipt that does not get recorded in RocksDB, so you won't be able to query it with `GetReceipt`), we may ignore these cases as those are not fees or gas refund receipts.

2022-10-19 10:12 UTC, matklad approved these changes

2022-10-19 12:24 UTC, nikurt commented on chain/rosetta-rpc/src/adapters/transactions.rs
> +    let receipt_view = view_client.send(near_client::GetReceipt { receipt_id }).await.ok()?.ok()?;
```suggestion
    let receipt_view = view_client.send(near_client::GetReceipt { receipt_id }.with_span_context()).await.ok()?.ok()?;
```

2022-10-19 12:48 UTC, merged