near-store: simplify Store::save_to_file and Store::load_from_file
near/nearcore pull request #8424
Opened 2023-01-24 01:15 UTC by mina86

On writing side, use borsh in Store::save_to_file.  Borsh does exactly
what we want and using it turns five lines of code into one.

On reading side, check for EOF explicitly which removes the somewhat
convoluted match on the result of read_u32 and unifies how reading key
and value look.

2023-01-24 12:01 UTC, Longarithm commented
cc @pugachAG because he also works with these methods rn: https://github.com/near/nearcore/pull/8417
I think that test makes strong sense, and if it doesn't interfere much with work on #8417, I can take a look and approve.

2023-01-24 12:52 UTC, pugachAG commented on core/store/src/lib.rs
> +            borsh::to_writer(&mut file, &item?)?
I personally find it a bit confusing to start relying on the fact that `borsh` coincidentally encodes this the same way as we want here. Especially considering that we don't use it when decoding values. I would rather prefer having `write_vec` method (similar to the newly added `read_vec`) to explicitly writes bytes.

2023-01-24 12:56 UTC, pugachAG commented
> cc @pugachAG because he also works with these methods rn: #8417 I think that especially a test here makes strong sense, and if it doesn't interfere much with work on #8417, I can take a look and approve.

@Longarithm Thanks for flagging this. It doesn't seem to be in the way of #8417, so we can proceed here and then I will update my implementation. @mina86 you can also include changes from #8417 in this PR if you prefer that.

2023-01-24 15:59 UTC, pugachAG approved these changes
Thanks for including #8417 into this!

2023-01-25 10:32 UTC, pugachAG requested changes
Let's not enable nayduck tests as part of this PR. This is not enough to fully enable flat storage as Alex explained in [this comment](https://github.com/near/nearcore/pull/8417#issuecomment-1400534027).

2023-01-25 13:52 UTC, mina86 commented
Done.

2023-01-25 13:58 UTC, pugachAG approved these changes
LGTM @Longarithm could you please stamp this

2023-01-25 15:46 UTC, Longarithm approved these changes

2023-01-25 15:57 UTC, merged