draft: store items in flat storage deltas separately
near/nearcore pull request #8475
Opened 2023-01-31 14:43 UTC by Longarithm

2023-02-08 04:37 UTC, mzhangmzz reviewed
I'm confused how this PR limits the memory usage of deltas. It only changes the storage format of how deltas are stored, but doesn't actually limit the deltas in memory. Do you plan to change that?

In this PR, I see that even though deltas are stored in storage in key value pairs separately, but deltas are still loaded into memory as a whole in `FlatStateDelta::read_from_store` function. I want to confirm that you don't plan to change that because I just realized a potential issue with reading delta key value pairs from storage separately instead of loading it entirely.  If we have a in memory cache for deltas in memory and only load/purge (block_hash, key) keys into this cache on demand in the `get_ref` function, then there will be a cache miss every time if a key is not in a block delta. In the worse case, even if a block has no change and has an empty delta, all lookups for the key in this block will not be found in the cache and must hit storage. If we always load deltas into memory as a whole and also stores information of which block deltas are in memory, we can avoid that.

2023-02-09 06:18 UTC, mzhangmzz reviewed
LGTM!

2023-02-09 06:18 UTC, mzhangmzz approved these changes

2023-02-09 10:06 UTC, pugachAG requested changes
> we also store an empty key-value pair indicating the delta existence

This looks like a hack to me. Can we instead just read prefix until we reach the next block?

2023-02-09 10:06 UTC, pugachAG commented on core/store/src/flat_state.rs
> +        out.extend(block_hash.as_bytes());
this is part of encoding logic which is duplicated in `encode`, lets extract this to a separate method, something like `fn append_prefix(out: &mut Vec<u8>, shard_id: ShardId, block_hash: CryptoHash)` or `fn encode_prefix(shard_id: ShardId, block_hash: CryptoHash) -> [u8;40]` and then append it

2023-02-09 11:22 UTC, Longarithm commented
> Can we instead just read prefix until we reach the next block?

Could you clarify what do you mean?

Without that, there is no way to distinguish between cases "delta was saved but it is empty" and "delta was not saved yet". I think there is a small benefit to have it, because if delta was not saved incorrectly, we can throw an error. Do you see more convenient way to do it, or it doesn't look like a benefit to you?

2023-02-09 11:33 UTC, pugachAG commented
> there is no way to distinguish between cases "delta was saved but it is empty" and "delta was not saved yet"

when do we need to distinguish between those cases?

2023-02-09 12:04 UTC, Longarithm commented
> when do we need to distinguish between those cases?

We need to do it in `test_flat_storage_creation`. One of checked behaviours is that we do not save deltas before migration start, but do save deltas after that. Why this is needed is documented (or should be) in `FlatStorageCreationStatus`.

2023-02-09 12:07 UTC, pugachAG commented
@Longarithm 

In this case I suggest creating a separate column for that to store flat state delta metadata.

2023-02-09 12:21 UTC, Longarithm commented
It makes sense, then we can have two separate methods `FlatStateDelta::read_from_store` and `FlatStateDelta::exists` reading from these separate columns.

@mzhangmzz does it make sense to you - because you took part in implementing some of that logic?

2023-02-27 18:31 UTC, Longarithm commented
We reconsidered approach to https://github.com/near/nearcore/issues/8436 (summary is updated there) and decided not to proceed with it. For MVP, deltas as a single DB entry are fine.

2023-02-27 18:31 UTC, closed without merging