feat: Rosetta supports delegate action
near/nearcore pull request #8750
Opened 2023-03-17 11:31 UTC by encody

Ref #8469

2023-03-21 14:18 UTC, encody commented on chain/rosetta-rpc/src/adapters/validated_operations/signed_delegate_action.rs
> -    pub(crate) signature: crate::models::Signature,
This type of signature encodes more information than the native `Action` does

2023-03-21 14:25 UTC, encody commented on chain/rosetta-rpc/src/adapters/validated_operations/signed_delegate_action.rs
> -    pub(crate) signature: crate::models::Signature,
It also only appears in metadata that we control

2023-03-21 14:26 UTC, encody commented on chain/rosetta-rpc/src/adapters/validated_operations/delegate_action.rs
> -            operations: non_delegate_operations,
Removing nested operations (otherwise the operations list appears twice in the output: once nested and once flat)

2023-03-22 11:29 UTC, akhi3030 commented
@firatNEAR: I don't think you have codeowner rights.  Let me know when you are happy with the PR and I can greenlight it.

2023-03-22 11:53 UTC, firatNEAR requested changes

2023-03-22 11:54 UTC, firatNEAR approved these changes

2023-03-22 12:39 UTC, akhi3030 commented
@firatNEAR, @encody: should another engineer in the protocol also review the PR or are you comfortable merging?

2023-03-23 02:40 UTC, encody commented
@akhi3030 This is only an update to the Rosetta RPC.

2023-03-23 07:56 UTC, encody commented on chain/rosetta-rpc/src/adapters/validated_operations/delegate_action.rs
> +        let mut non_delegate_operations: Vec<crate::models::NonDelegateActionOperation> = vec![];
i blame clippy for this

2023-03-23 07:58 UTC, firatNEAR commented on chain/rosetta-rpc/src/adapters/validated_operations/delegate_action.rs
> +        let mut non_delegate_operations: Vec<crate::models::NonDelegateActionOperation> = vec![];
Let's make sure that we don't have `dead code` lying around.

2023-03-23 08:08 UTC, firatNEAR commented
> @firatNEAR, @encody: should another engineer in the protocol also review the PR or are you comfortable merging?



> @firatNEAR, @encody: should another engineer in the protocol also review the PR or are you comfortable merging?

I think we are confident with this PR being merged after the comments are resolved.

2023-03-24 08:05 UTC, encody commented
Merge because of possibly spurious test failure.

2023-03-24 08:35 UTC, merged