chore: Publish `near-vm-runner` and it's dependencies
near/nearcore pull request #8782
Opened 2023-03-23 11:30 UTC by khorolets

My previous PR #8762 was reverted by #8780 because release automation was broken.

Looks like the cause of broken automation was a crate `near-test-contract`. We had a discussion about this package and the reasons to publish it in the first place in the very first PR. Now we have proof that a dependency that mentioned in the `dev-dependencies` section of `Cargo.toml` is not required to be published to crates.io.

Once figured out I created a PR #8779 but it was unnoticed and instead all the changes were reverted in #8780.

As agreed with @jakmeier I am creating the same changes but disabled `near-test-contract` for publishing necessary crates in the future.

2023-03-23 11:36 UTC, jakmeier commented
Also @khorolets it seems this doesn't work, as even pre-commit fails:

```
(i) These private crates break publishable crates. Either make these private crates publishable or avoid using them in the publishable crates:
--
<span class="term-fg31">🚨 Error: The command exited with status 1</span>
```

2023-03-23 12:46 UTC, miraclx requested changes
Blocker resolved in https://github.com/near/nearcore/pull/8785. One little thing.

2023-03-23 12:46 UTC, miraclx commented on runtime/near-test-contracts/LICENSE-APACHE
Let's symlink to the licenses in https://github.com/near/nearcore/tree/master/licenses instead.

2023-03-24 09:35 UTC, khorolets commented
@andrei-near @jakmeier jobs are green now, thanks to @miraclx

2023-03-24 17:27 UTC, nagisa commented
I believe https://github.com/near/near-ops/blob/a7dbb2cc47addaf3cb294e07c269964c8051c41c/buildkite/pipelines/nearcore-release.yml#L37-L55 is the part that's responsible for publishing the crates. Unfortunately that's not particularly helpful here, as this `cargo ws` does not support `--dry-run`. But since we do use a fork of it for publishing already, we can also look into adding `--dry-run` for it, I guess.

Either way, this is more complicated than I initially anticipated, so I'm not going to block this change on that…

2023-03-27 10:21 UTC, jakmeier commented
In that case, coming back to @andrei-near : Do you want to check if the canary build fails again, which you pointed out for the now reverted PR in [Zulip](https://near.zulipchat.com/#narrow/stream/295302-general/topic/publishing.20nearcore.20crates/near/343928649), or do you think we can merge this as is?

2023-03-30 14:42 UTC, Ekleog-NEAR commented
I tried thinking a bit about it, but having a `cargo ws publish --dry-run` would be highly nontrivial, as one crate would depend on another in order to be published, so it could not rely on `cargo publish --dry-run` at all. I think the best that could be done might be using another rust target folder and checking that `cargo test` passes for each crate with `publish = true`, plus verifying that crates with `publish = true` can only depend on crates with `publish = true`… but as @nagisa says, it would be hard to actually do this.

TBH I’m not sure the current "bump the version in cargo.toml and CI will publish the changes" scheme is the best one, as CI failures are silent in this case, but I guess anything better would be hard to switch to.

2023-04-03 09:52 UTC, jakmeier approved these changes
It seems there are no simple ways to fix this for now and @andrei-near hasn't raised any concerns with merging this, so should we just merge this and check all post-merge CI jobs?

And then while working on limited-replayability, maybe @Ekleog-NEAR you can think more about how the ideal process of publishing would look like? I'd say we can circle back to improve the process once we know how limited-replayability is implemented.

2023-04-17 18:47 UTC, merged

2023-04-18 08:48 UTC, Ekleog-NEAR commented
Uhh just noticed this, thank you for merging and sorry for not having noticed I had forgotten to set the automerge label!