fix(state-viewer): print tree shows hash and memory usage
near/nearcore pull request #8919
Opened 2023-04-18 10:29 UTC by nikurt

* makes `neard view-chain --format full` print hash and node's memory usage.
* adds an action 'print' to `neard view-state state-part apply` to print the sub-tree contained in a state part.
* fixes `neard view-state-part dump` to print state record in a human readable way.

2023-04-18 15:55 UTC, nikurt commented
cc: @Longarithm

2023-04-18 15:57 UTC, akhi3030 commented
assigning @Longarithm as the reviewer.

2023-04-25 14:54 UTC, Longarithm requested changes

2023-04-25 14:54 UTC, Longarithm commented on tools/state-viewer/src/state_parts.rs
>      Apply {
Looks good, the only concern I have here is readability. When I read "apply", I assume that something is applied/changed, but now we can have validate and print actions which doesn't modify anything.

I suggest to rename parent action to `Load`, similarly to python `json` load & dump API, and have `LoadAction` and `load_state_parts` to show that we read state parts from somewhere. Inside we have `Apply` action which means that we also apply part to state, etc.

2023-04-25 15:08 UTC, Longarithm approved these changes

2023-04-25 15:08 UTC, Longarithm commented on tools/state-viewer/src/state_parts.rs
>          assert!(part_id < num_parts, "part_id: {}, num_parts: {}", part_id, num_parts);
in the comment above: "Applying state as seen at the beginning of the specified epoch." -> "Loading state as seen at the beginning of the specified epoch."

2023-04-25 15:08 UTC, Longarithm commented on tools/state-viewer/src/state_parts.rs
>      tracing::info!(target: "state-parts", total_elapsed_sec = timer.elapsed().as_secs_f64(), "Applied all requested state parts");
```suggestion
    tracing::info!(target: "state-parts", total_elapsed_sec = timer.elapsed().as_secs_f64(), "Loaded all requested state parts");
```

2023-04-25 15:08 UTC, Longarithm commented on tools/state-viewer/src/state_parts.rs
> +    /// Load all or a single state part of a shard and perform an actions wth those parts.
```suggestion
    /// Load all or a single state part of a shard and perform an action wth those parts.
```

2023-04-25 15:35 UTC, merged