chore: update borsh dependency
near/nearcore pull request #9432
Opened 2023-08-15 11:51 UTC by dj8yfo

This pr is targeted to resolve sub-issue of [#51 of near/borsh-rs](https://github.com/near/borsh-rs/issues/51)

- [ ] test alpha release on nearcore and capture migration guide steps, create a draft PR (only merge after 1.0.0 release)
  - [ ] update [zeropoolnetwork/bn](https://github.com/zeropoolnetwork/bn) to work with alpha/1.0.0 release.

2023-10-08 10:47 UTC, frol commented
@dj8yfo Please, update to borsh 1.0, rebase, and let's merge it 🙏

2023-10-09 19:52 UTC, frol requested changes
Oh, I totally did not expect so many places needed https://docs.rs/borsh/latest/borsh/fn.object_length.html

2023-10-09 19:52 UTC, frol commented on chain/network/src/types.rs
> +#[borsh(use_discriminant = false)]
I am glad we took another mile to fix that hidden footgun of "silently" changing the default from `false` to `true`.

@mina86 Thanks for calling that out!

2023-10-09 19:52 UTC, frol commented on core/store/benches/finalize_bench.rs
> +    let num_chunks = memory_range / borsh::to_vec(&chunk).unwrap().len();
This can use https://docs.rs/borsh/latest/borsh/fn.object_length.html, right?

2023-10-09 19:52 UTC, frol commented on core/store/src/genesis/state_applier.rs
> +                    + borsh::to_vec(&access_key).unwrap().len() as u64;
https://docs.rs/borsh/latest/borsh/fn.object_length.html

2023-10-09 19:52 UTC, frol commented on core/store/src/trie/split_state.rs
> +                    });
1. https://docs.rs/borsh/latest/borsh/fn.object_length.html
2. .iter().map().sum() instead of fold

2023-10-09 19:52 UTC, frol commented on genesis-tools/genesis-populate/src/state_dump.rs
>              file.write_all(&data)?;
[I think we can directly write to the file here since borsh supports to_writer](https://docs.rs/borsh/latest/borsh/fn.to_writer.html)

2023-10-09 19:52 UTC, frol commented on integration-tests/src/tests/client/benchmarks.rs
> +    let size = borsh::to_vec(&chunk).unwrap().len();
https://docs.rs/borsh/latest/borsh/fn.object_length.html

2023-10-09 19:52 UTC, frol commented on integration-tests/src/tests/client/features/zero_balance_account.rs
> +    );
https://docs.rs/borsh/latest/borsh/fn.object_length.html

2023-10-09 19:52 UTC, frol commented on runtime/runtime/src/actions.rs
> +            + borsh::to_vec(&access_key).unwrap().len() as u64
https://docs.rs/borsh/latest/borsh/fn.object_length.html

same for several more occurrences in this file

2023-10-09 19:52 UTC, frol commented on runtime/runtime/src/verifier.rs
> +                                + borsh::to_vec(&access_key).unwrap().len() as u64
https://docs.rs/borsh/latest/borsh/fn.object_length.html

2023-10-09 19:52 UTC, frol commented on tools/amend-genesis/src/lib.rs
> +                        + borsh::to_vec(&access_key).unwrap().len() as u64
https://docs.rs/borsh/latest/borsh/fn.object_length.html

2023-10-10 08:57 UTC, frol approved these changes
@dj8yfo Well done!

2023-10-10 10:44 UTC, Longarithm commented
Looks great. Minor non-blocking question - why `try_to_vec` was deprecated? Couldn't find the reason in migration guide.

2023-10-10 10:45 UTC, Longarithm approved these changes

2023-10-10 11:10 UTC, merged

2023-10-10 12:11 UTC, dj8yfo commented
> Looks great. Minor non-blocking question - why `try_to_vec` was deprecated?

@matklad suggested that it didn't make sense to override this trait method => it should not be a trait method, but rather an external helper. Couldn't come up with counterexamples. It may make sense to override initial vector allocation capacity per type, but that can be done with introducing a constant on `BorshSerialize` trait.
Besides, it kinda looks compact, fully qualified, cool and uniform with `serde_json::to_vec`. 

>  Couldn't find the reason in migration guide. 

i think more context can be found by following a trail hyperlinks, reachable from migration guide

2023-10-10 17:13 UTC, matklad commented
Specific reasons here:

* to mirror `serde::to_vec` API. Serde is extremely popular, mirroring its API is good just for that reason.
* `borsh::to_vec(&val)` is more obvious at call-site than `x.try_to_vec`, for two reasons:
  * It doesn't require trait import (and the associated method resolution reasoning)
  * In `x.try_to_vec`, _nothing_ mentions borsh; that's not great for a method available on a wide array of types.

2023-10-10 17:14 UTC, frol commented
> Couldn't find the reason in migration guide.

It was useful for borsh-rs developers and for those who will also need to migrate from older version of borsh to the new one. nearcore team is lucky one for getting the migration done by borsh-rs maintainer, but solana who uses borsh-rs is not that lucky :-P