[memtrie] (1/n) Add MemTrieNode, an efficient in-memory trie node structure.
near/nearcore pull request #9516
Opened 2023-09-12 18:48 UTC by robin-near

This is the first step towards implementing the efficient in-memory data structure for the in-memory trie prototype mentioned here https://near.zulipchat.com/#narrow/stream/295558-pagoda.2Fcore/topic/Stateless.20validation.20-.20putting.20all.20state.20in.20memory

2023-09-13 10:58 UTC, Ekleog-NEAR requested changes
This is a half-review: I only looked at `flexible_data` for now, though I’ll try to look at `node` later :) The idea looks nice, and the abstraction interesting!

My first thought would be, however deeply we review this, it’ll continue to have quite a lot of unsafe. So we probably need to fuzz it, so that we run it through ASAN and it can catch mistakes we could have missed! To do that, you can add a test like [this one](https://github.com/near/nearcore/blob/9ddfd49fb33288a43dc0ed8f4a37d66a11e69531/core/account-id/src/serde.rs#L65-L77), assuming you don’t plan on landing this into production before 2-3 months it should have some time to run on our infra by then :) (right now the test won’t run because we require a much more complex for fuzzing, but I’m currently working towards making tests as simple as this run as fuzzers)
You can also get types more complex than just `&[u8]` if needed, see [this example in the documentation](https://camshaft.github.io/bolero/features/structured-testing.html), though AFAIR there still are some issues with recursive types.

Also, another thought I had was, can we remove the concept of `from_input`? In particular, would it be possible to just have `encode_flexible_data` and `decode_flexible_data` transparently write/read the header and the flexible data just after it? It might reduce the likelihood of mistakes.

And the other big thing would be, replacing the use of pointers in the API with mutable slices for RawEncoder/encode_flexible_data and immutable slices for RawDecoder/decode_flexible_data. WDYT?

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +    pub unsafe fn encode_flexible<T: FlexibleDataHeader>(
This doesn’t need to be unsafe

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +    pub unsafe fn finish(self) -> *const u8 {
This doesn’t need to be unsafe. The only question would be, were all the bytes actually allocated, and this should probably be handled by just returning `*const MaybeUninit<u8>`, which’d come naturally with the suggested changes in `fn new()`

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +/// the memory being decoded from.
If I understand the requirements for `'a` correctly, this should just be `data: &'a [u8]` (and probably `&'a [MaybeUninit<u8>]` as per the above)

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +    unsafe fn ptr(&mut self) -> *const u8 {
This probably doesn’t need to be unsafe, like for RawEncoder.

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +    pub unsafe fn decode<T>(&mut self) -> &'a T {
Needs documentation of the safety requirements, here that a `T` was encoded here, and that `T` has an alignment of `1`, as a reference to the `T` is being made with no copy and AFAICT no alignment verification. It’d probably deserve at least a `debug_assert!(std::mem::align_of::<T>() == 1)`.

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +    pub unsafe fn decode_as_mut<T>(&mut self) -> &'a mut T {
See above.

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +    pub unsafe fn peek<T>(&mut self) -> &'a T {
See above. Plus an additional safety requirement: the next decode called must not be `decode_as_mut`; as it’d make both a mutable and an immutable reference to the same memory location.

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +    pub unsafe fn decode_flexible<T: FlexibleDataHeader>(&mut self, header: &'a T) -> T::View<'a> {
See above.

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +    pub unsafe fn take_fixed<T>(&mut self) -> T {
See above. Also, why not just use `std::ptr::read(self.ptr() as *mut T)`? I don’t see why you’d need to overwrite the current memory location with new uninitialized data; the old data is perfectly good uninitialized data :)

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +    pub unsafe fn drop_flexible<T: FlexibleDataHeader>(&mut self, header: &T) {
See above.

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/encoding.rs
> +    pub unsafe fn take_encoded_data(&self) -> Box<[u8]> {
Should give out `Box<[MaybeUninit<u8>]>`. Also, should take `self` and not `&self`, as there’s definitely no way this object will still be valid after running this.

Considering how this function means `RawDecoder` took ownership of the data, I’d suggest also making it take in `Box<[MaybeUninit<u8>]>` in `fn new()`. If it cannot, then this function is probably not something that should be here, as it assumes there is actually a `Box` that has been `into_raw`ed and can be recovered.

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/extension.rs
> +        EncodedExtensionHeader { length: extension.len() as u16 }
Nit: panic if `extension.len() > u16::MAX`. Or at least a `debug_assert` and a comment about it, if it’s supposed to be guaranteed by other parts of the system. Seems like safety does not depend on it anyway, which is good :)

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/mod.rs
> +    unsafe fn encode_flexible_data(&self, data: Self::InputData, ptr: *mut u8);
> This function must be implemented in a way that writes exactly `self.flexible_data_length()` bytes to the given memory location.

This is a requirement on the trait implementer, so this should be `pub unsafe trait` and not only `pub trait`

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/mod.rs
> +    /// Drops any objects encoded in the flexible data.
This should tell again the safety requirements at least for the caller; as the user might just give a look at the rustdoc of this function and not look at the functions around.

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/value.rs
> +                EncodedValueHeader { length_and_inlined: value_ref.length }
`assert!(value_ref.length < INLINED_MASK)`

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/value.rs
> +                assert!(v.len() as u32 & Self::INLINED_MASK == 0);
Same, `assert!(v.len() < INLINED_MASK as usize)`, to avoid issues with `v.len() > u32::MAX`, however unlikely that is.

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/value.rs
> +                assert!(!inlined);
These two could be `debug_assert`, as the safety requirements already require that `value` is the same that was passed to `from_input`

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/value.rs
> +                *(ptr as *mut CryptoHash) = value_ref.hash;
```suggestion
                (*(ptr as *mut MaybeUninit<CryptoHash>)).write(value_ref.hash);
```
Or you’ll be dereferencing and then dropping an uninit cryptohash

2023-09-13 10:58 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/value.rs
> +            ValueView::Inlined(std::slice::from_raw_parts(ptr, length as usize))
Here again, the lifetime is taken from `&'a self` instead of the actual requirement which is taking it from the `ptr: *const u8`. I think there’s still a chance we could replace these pointers with `&[MaybeUninit<u8>]`?

Or, the whole view infrastructure is very nice and tidy, but if it’s hard maybe it’d make sense to always copy-out? I have no idea how much perf we gain by not copying out, as I haven’t looked at the use cases yet.

2023-09-14 19:10 UTC, robin-near commented on core/store/src/trie/mem/flexible_data/value.rs
> +            ValueView::Inlined(std::slice::from_raw_parts(ptr, length as usize))
Let me address this one first - as it could affect all the other places.

I think things are generally a lot less unsafe if instead of casting pointers all over the place, I always operate the memory region as a Box<[u8]>. That means copying things out, serializing things in (BorshSerialize is good enough). There would be two places that remain unsafe:
 * serialized pointers - these children pointers for example. The unsafeness here is essentially that we're bypassing any sort of lifetime checks. Once we start mutating the trie, there's a risk here that we access freed memory if there's a bug.
 * keeping only a pointer to the memory allocation instead of a pointer and a size. This is to save 8 bytes per node, which is substantial. It's always possible to derive the size based on what we encoded in the buffer, but that is inherently unsafe. The risk here is we can buffer overflow or perform invalid deallocations, if there is a bug.

I'm also not sure how much perf gain there is by not copying, my guess is it's not much. But it's also difficult to make a View that has a static lifetime because it holds references to the children. So.... this is a head scratcher. I think I wanna try an alternative where the view has a static lifetime but only encodes pointers, and a higher level "reference to a root node" is required to dereference anything. The reference to root node ensures the lifetime of all its descendants, though also in an unsafe way.

Another thing is we can avoid memory safety issues entirely by just using indices in a giant array. There wouldn't be any UB even if the program panics because there's some logic bug. That was the idea for the file-backed trie but it also applies here for the memory safety aspect.

2023-09-19 04:48 UTC, Ekleog-NEAR commented on core/store/src/trie/mem/flexible_data/value.rs
> +            ValueView::Inlined(std::slice::from_raw_parts(ptr, length as usize))
> I think things are generally a lot less unsafe if instead of casting pointers all over the place, I always operate the memory region as a Box<[u8]>. That means copying things out, serializing things in (BorshSerialize is good enough).

Hmm… I don’t see why it’d force you to copy more things out? If you use Box<[MaybeUninit<u8>]>, then you only need to copy things out when you want to take ownership of them and not just get a reference to them. Which you’d already need to do with the current pointer-based system too.

However, if you mean by Box<[u8]> that you want to store serialized data, then indeed you need to copy things out. And it’ll probably reduce unsafety quite a lot, but I guess you’ll need to check that performance is indeed significantly improved, as the "only" 3x improvement over rocksdb-with-hot-cache could easily vanish. Also, I’m not entirely sure what exactly you’d want to serialize, so I can’t speak much more about it right now. Also, as you mention 8 bytes per node is a lot, borsh serialization can have IIRC quite a bit of overhead.

> The risk here is we can buffer overflow or perform invalid deallocations, if there is a bug.

I don’t see how you could perform invalid deallocations, if you keep everything in Box<[u8]>, as Box will deal with the deallocation.

-----

Honestly, I don’t think I understand well enough the new idea you’re mentioning to be able to properly give an opinion on it. And I understand even less the part about static lifetimes and root nodes. Sorry about that 😅 

To clarify my point about copying things out, it was just that `ValueView` does not actually borrow the right parameter. It needs `ptr` to be alive for `'a` but it only guarantees that `self` will be. So copying things out (just by having the same code and then calling `.to_owned()`) would be enough to fix that problem.

2023-09-20 16:32 UTC, robin-near commented on core/store/src/trie/mem/flexible_data/value.rs
> +            ValueView::Inlined(std::slice::from_raw_parts(ptr, length as usize))
The new idea is https://github.com/near/nearcore/pull/9541 I think you would agree that this is a whole lot safer :)

2023-09-20 16:33 UTC, robin-near commented
Deprecating this in favor of https://github.com/near/nearcore/pull/9541 which is a lot safer, saves even more memory, and which further development has already been started on top of.

2023-09-20 16:33 UTC, closed without merging